import { ProgramLayout } from "@/components/programs/ProgramLayout";

export default function BashundharaPage() {
  return (
    <ProgramLayout
      title="Bashundhara Enterprise"
      subtitle="Empowering rural communities through sustainable agricultural commerce."
      heroImage="https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=1200&q=80"
      stats={[
        { value: "45,000", label: "Farmers Empowered" },
        { value: "$2M+", label: "Micro-loans Disbursed" },
        { value: "100%", label: "Fair Trade Certified" },
        { value: "65%", label: "Female Artisans" }
      ]}
      challengeText={
        <>
          <p>
            Despite agriculture being the backbone of Bangladesh's economy, millions of rural farmers and artisans remain trapped in poverty. They are often exploited by middlemen, lack access to modern farming techniques, and have no direct linkage to profitable urban markets.
          </p>
          <p>
            Without fair compensation and financial literacy, these hard-working individuals cannot expand their businesses, invest in their children's education, or build a financial safety net for their families.
          </p>
        </>
      }
      approachText={
        <>
          <p>
            Bashundhara operates as a Social Enterprise—a business model designed to maximize social impact rather than private profit. We cut out the middlemen by connecting rural producers directly to commercial markets.
          </p>
          <p>
            By providing micro-financing, modern agricultural training, and fair-trade platforms, we ensure that the wealth generated by rural communities stays within those communities. All surplus profits generated by the Bashundhara enterprise are reinvested directly into WOLT Foundation's humanitarian programs.
          </p>
        </>
      }
      interventions={[
        {
          title: "Micro-Financing",
          description: "Providing low-interest, accessible micro-loans to rural entrepreneurs, farmers, and artisans to help them scale their production and purchase high-quality raw materials."
        },
        {
          title: "Fair-Trade Market Linkages",
          description: "Establishing direct supply chains between rural producers and urban retail markets, ensuring farmers receive premium prices for their goods without exploitation."
        },
        {
          title: "Agricultural Modernization",
          description: "Training farmers in high-yield, organic, and climate-resilient farming techniques to maximize their crop output and sustainability."
        },
        {
          title: "Women's Economic Empowerment",
          description: "Focusing specifically on rural women weavers and artisans, providing them with the capital, skills, and market access needed to achieve financial independence."
        }
      ]}
      quote={{
        text: "True empowerment is not giving someone a handout, but giving them the tools and the market access to build their own prosperity.",
        author: "Nusrat Jahan, Director of Social Enterprises"
      }}
    />
  );
}
