import { FileText, Download, BarChart2 } from "lucide-react";
import Link from "next/link";

export default function ResearchPage() {
  const publications = [
    {
      title: "Annual Impact Report 2023-2024",
      type: "Annual Report",
      pages: 124,
      size: "4.2 MB",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=400&q=80"
    },
    {
      title: "Climate Vulnerability Assessment: Coastal Belt",
      type: "Research Paper",
      pages: 45,
      size: "2.1 MB",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=400&q=80"
    },
    {
      title: "Mental Health Stigma in Rural Bangladesh",
      type: "Policy Brief",
      pages: 12,
      size: "0.8 MB",
      image: "https://images.unsplash.com/photo-1527137342181-19aab11a8ee8?auto=format&fit=crop&w=400&q=80"
    },
    {
      title: "Economic Impact of Bashundhara Fair Trade Model",
      type: "Case Study",
      pages: 28,
      size: "1.5 MB",
      image: "https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=400&q=80"
    }
  ];

  return (
    <div className="min-h-screen bg-slate-50 pb-24">
      {/* Hero Section */}
      <section className="bg-slate-900 pt-24 pb-16">
        <div className="container mx-auto px-4 text-center">
          <div className="w-16 h-16 bg-pink-600/20 text-pink-400 rounded-2xl flex items-center justify-center mx-auto mb-6">
            <BarChart2 className="w-8 h-8" />
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-white mb-4">Research & Publications</h1>
          <p className="text-lg text-slate-300 max-w-2xl mx-auto">Data-driven insights, annual reports, and policy briefs generated by our research and evaluation teams.</p>
        </div>
      </section>

      {/* Content Section */}
      <section className="container mx-auto px-4 mt-16 max-w-7xl">
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {publications.map((pub, idx) => (
            <div key={idx} className="bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all border border-slate-200 group flex flex-col">
              <div className="relative h-48 overflow-hidden bg-slate-100 p-8 flex items-center justify-center">
                <div className="absolute inset-0">
                  <img src={pub.image} alt="cover" className="w-full h-full object-cover opacity-20 group-hover:opacity-30 transition-opacity" />
                </div>
                <FileText className="w-20 h-20 text-slate-300 relative z-10 group-hover:text-blue-500 transition-colors group-hover:scale-110 duration-300" strokeWidth={1} />
                <div className="absolute top-4 left-4 bg-white text-slate-700 text-[10px] font-bold uppercase tracking-wider px-3 py-1.5 rounded-full shadow-sm">
                  {pub.type}
                </div>
              </div>
              <div className="p-6 flex flex-col flex-grow">
                <h3 className="text-lg font-bold text-slate-900 mb-4 line-clamp-2">{pub.title}</h3>
                <div className="text-sm text-slate-500 mb-6 flex items-center gap-4">
                  <span>{pub.pages} Pages</span>
                  <span>•</span>
                  <span>{pub.size}</span>
                </div>
                <div className="mt-auto">
                  <button className="w-full inline-flex items-center justify-center gap-2 text-sm font-bold text-blue-600 hover:text-blue-800 transition-colors bg-blue-50 hover:bg-blue-100 py-3 rounded-xl">
                    <Download className="w-4 h-4" /> Download PDF
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
